### ISSUE TITLE
Snapfactor is not supported on the storageclass

### ISSUE THREAD

**Issue by kannanvr** [heketi/heketi#1498]
Hi,
   I have created the Storageclass with snapfactor as 10. 
When i create the PVC, i am getting the below error from provisoner.
```
  Warning  ProvisioningFailed  3s (x2 over 18s)  persistentvolume-controller  Failed to provision volume with StorageClass "fast": invalid option "snapfactor" for volume plugin kubernetes.io/glusterfs
```

Following is my storageclass yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://127.0.0.1:8080"
  restuser: "admin"
  secretName: "admin"
  volumetype: "replicate:3"
  snapfactor: "10"
```

Does heketi supports snapfactor or not?
