### ISSUE TITLE
Clarification: volume creation with durability none and storage class with replicate

### ISSUE THREAD

**Issue by imranrazakhan** [heketi/heketi#1668]
### Kind of issue
> Clarification

### Observed behavior
I am installing Openshift+glusterfs on two nodes, As default it expect 3 nodes but we can install with following two option and want to know difference between them?

1-  While creating volume add durability=none and create storageclass with replicate:2 options
2- Or While creating volume add --replica=2 

So whats difference between both?

**StorageClass:**
```
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: glusterfs-storage
parameters:
  resturl: http://heketi-storage.glusterfs.svc:8080
  restuser: admin
  secretName: heketi-storage-admin-secret
  secretNamespace: glusterfs
  volumetype: "replicate:2"
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
### Information about the environment:

- Heketi version used (e.g. v8.0.0 or master): 8.0.0
- Operating system used:  CentOS
- Using kubernetes, openshift, or direct install:  Openshift 3.11
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: Outside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):  Openshift-ansible
