### ISSUE TITLE
Set label on created PVC

### ISSUE THREAD

**Issue by askya** [heketi/heketi#1820]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
Feature request

### Observed behavior
When I create pvc, heketi create PV for it and that is ok.
It comes that I delete the PVC (The PV is released & reclaim policy is retain) and recreate it with the same manifest. Heketi create a new PV for it also.
Then I set a label on my PVC, and I get the error when describing my PVC  `Failed to provision volume with StorageClass "bot-gluster": not able to parse your claim Selector`

### Expected/desired behavior
PVC containing selector is parsed, and if PV doesn't exist, the PV which will be provisioned for it will have the label of the PVC.

### Details on how to reproduce (minimal and precise)
Install glusterfs on kubernetes worker nodes
Deploy  heketi as  deployment on kubernetes
Create cluster with topology.
Create storage class
```
apiVersion: v1
kind: Secret
metadata:
  name: heketi-pass
data:
  # base64 encoded password. E.g.: echo -n "mypassword" | base64
  key: JUDHlopUJGK=
type: kubernetes.io/glusterfs
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bot-gluster
provisioner: kubernetes.io/glusterfs
parameters:
  #resturl: "http://10.97.122.241:8080"
  resturl: "http://10.11.1.26:31021"
  #resturl: "http://heketi.default.svc.cluster.local:8080"
  restauthenabled: "true"
  restuser: "admin"
  secretNamespace: "default"
  secretName: "heketi-pass"
  volumetype: "replicate:3"
  volumenameprefix: "bot"
reclaimPolicy: Retain
allowVolumeExpansion: true
```
Create PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpvc
spec:
  selector:
    matchLabels:
      app: tpvc
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: bot-gluster
```

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  10
- Operating system used: Centos 8
- Heketi compiled from sources, as a package (rpm/deb), or container:  Container
- If container, which container image: heketi/heketi:10
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: outside (systemd)
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): custom (https://github.com/heketi/heketi/blob/master/docs/design/kubernetes-integration.md)
