### ISSUE TITLE
Failed to provision volume with StorageClass \"gluster-heketi-storageclass\": failed to create volume: failed to create volume: see kube-controller-manager.log for details

### ISSUE THREAD

**Issue by huyouba1** [heketi/heketi#1899]
ENV：
kubernetes 1.20.0rp
glusterfs-server-6.10-1.el7.x86_64
heketi-8.0.0-1.el7.x86_64
heketi-client-8.0.0-1.el7.x86_64

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-heketi-storageclass
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Retain
parameters:
  resturl: "http://1xxxxxxx:18080"
  restauthenabled: "true"
  restuser: "admin"
  secretName: "heketi-secret"
  secretNamespace: "default"
  #volumetype: "none"
  volumetype: "replicate:3"
  clusterid: "60d0c41c0b232906f90b528fbb58400a"
```

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-vol-pvc02
  namespace: default
spec:
  storageClassName: gluster-heketi-storageclass
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```

kubectl describe pvc glusterfs-vol-pvc02

```
 Failed to provision volume with StorageClass "gluster-heketi-storageclass": failed to create volume: failed to create volume: see kube-controller-manager.log for details
```

```
 heketi-cli  --user admin --secret admin --server http://k8s-master1:18080 topology info

Cluster Id: 60d0c41c0b232906f90b528fbb58400a

    File:  true
    Block: true

    Volumes:

    Nodes:

	Node Id: 46e7b325ce20528bf8160d8c65a3c652
	State: online
	Cluster Id: 60d0c41c0b232906f90b528fbb58400a
	Zone: 1
	Management Hostnames: xxxx
	Storage Hostnames: xxxx
	Devices:
		Id:04041ffb900f9e8a2d73cdd9a32ed62a   Name:/dev/sdb            State:online    Size (GiB):99      Used (GiB):0       Free (GiB):99
			Bricks:

	Node Id: 524481c119e6295117979bb80046f9c8
	State: online
	Cluster Id: 60d0c41c0b232906f90b528fbb58400a
	Zone: 1
	Management Hostnames: xxxxx
	Storage Hostnames: xxxx
	Devices:
		Id:a161942c4ea242e92cb753a18abc0483   Name:/dev/sdb            State:online    Size (GiB):99      Used (GiB):0       Free (GiB):99
			Bricks:

	Node Id: 918f73f5e17662abbcd0552445a53766
	State: online
	Cluster Id: 60d0c41c0b232906f90b528fbb58400a
	Zone: 1
	Management Hostnames: xxxx
	Storage Hostnames: xxxx
	Devices:
		Id:c0307d49fd4e8b3a5bd2b4ed48c4dcd9   Name:/dev/sdb            State:online    Size (GiB):99      Used (GiB):0       Free (GiB):99
			Bricks:
```

Please take a look
