### ISSUE TITLE
Use serviceAccountName to mount the secret volume

### ISSUE THREAD

**Issue by ant31** [heketi/heketi#615]
Hi, 

In kubernetes the certificates to access the api-master are automatically mounted on:
```
/var/run/secrets/kubernetes.io/serviceaccount 
```

and to select which serviceaccount certificate to mount, the key `pod.spec.serviceAccountName` can be used: 
```
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: heketi
  labels:
    glusterfs: heketi-deployment
  annotations:
    description: Defines how to deploy Heketi
spec:
  replicas: 1
  template:
    metadata:
      name: heketi
      labels:
        name: heketi
        glusterfs: heketi-pod
    spec:
      serviceAccountName: heketi-service-account
      containers:
      - image: heketi/heketi:dev
        imagePullPolicy: Always
        name: heketi
```
    
This will remove the need to manually enter secret name. 

The change would be to look in `/var/run/secrets/kubernetes.io/serviceaccount` to get the credentials.
