### ISSUE TITLE
Readiness probe failed: Job glusterd.service/start failed with result 'dependency' when deploying on kubernetes

### ISSUE THREAD

**Issue by harryge00** [heketi/heketi#656]
I have followed the exact tutorial as in https://github.com/heketi/heketi/tree/master/extras/kubernetes. After `kubectl create -f gluster-daemonset.json` and labeling, the glusterfs pods cannot be started:
```
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----			-------------			--------	------		-------
  53m		53m		3	{kubelet kube-node-1}	spec.containers{glusterfs}	Warning		Unhealthy	Readiness probe failed: ● glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

Jan 18 04:43:32 c3v112 systemd[1]: Dependency failed for GlusterFS, a clustered file-system server.
Jan 18 04:43:32 c3v112 systemd[1]: Job glusterd.service/start failed with result 'dependency'.

```

My kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2591+4f386031eb731a-dirty", GitCommit:"4f386031eb731af4371de5eac40c3d7af30117e0", GitTreeState:"dirty", BuildDate:"2017-01-05T08:29:41Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1+v0.11.1", GitCommit:"4f2f1033569539953f9dbd394f1c39149e00b636", GitTreeState:"clean", BuildDate:"2016-12-08T07:35:02Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by MohamedAshiqrh** [comment]
@harryge00 what operating system is kube nodes are running on and can you provide the rpcbind version.

**Comment by harryge00** [comment]
@MohamedAshiqrh  
Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-96-generic x86_64  

I don't know how to view the rpcbind version.
Inside container:
```
[root@c3v112 /]# rpcinfo -m
PORTMAP (version 2) statistics
NULL    SET     UNSET   GETPORT DUMP    CALLIT  
0       0/0     0/0     0/0     0       0/0     

RPCBIND (version 3) statistics
NULL    SET     UNSET   GETADDR DUMP    CALLIT  TIME    U2T     T2U     
0       0/0     0/0     0/0     0       0/0     0       0       0       

RPCBIND (version 4) statistics
NULL    SET     UNSET   GETADDR DUMP    CALLIT  TIME    U2T     T2U     
0       0/0     0/0     0/0     0       0/0     0       0       0       
VERADDR INDRECT GETLIST GETSTAT 
0       0       0       1   
```
On the host:
```
vagrant@c4v141:~$ rpcinfo -m
PORTMAP (version 2) statistics
NULL    SET     UNSET   GETPORT DUMP    CALLIT  
0       87/87   72/72   0/0     0       0/0     

RPCBIND (version 3) statistics
NULL    SET     UNSET   GETADDR DUMP    CALLIT  TIME    U2T     T2U     
0       89/116  29/29   0/0     3       0/0     0       0       0       

RPCBIND (version 4) statistics
NULL    SET     UNSET   GETADDR DUMP    CALLIT  TIME    U2T     T2U     
0       0/0     0/0     0/0     0       0/0     0       0       0       
VERADDR INDRECT GETLIST GETSTAT 
0       0       0       3 
```

**Comment by MohamedAshiqrh** [comment]
@harryge00 thanks a lot. Will get back to you soon.

**Comment by aliscott** [comment]
I'm seeing this issue when redeploying the glusterfs pods. `glusterd` won't start on the new pod until the old pod has fully terminated so it always fails the first readiness probe. Disabling `rpcbind.socket` and `rpcbind.service` on the host node doesn't have any effect.

**Comment by MohamedAshiqrh** [comment]
Ok @aliscott thanks a lot. Only dependency for gluster is rpcbind. For some reason rpc-bind is failing. If it is stopped in host and still If it is failing I am not sure(because I thought it is port conflict). @aliscott Is your setup similar to harryge00's setup.

**Comment by aliscott** [comment]
@MohamedAshiqrh I'm running:
CentOS Linux release 7.3.1611 (Core) with rpcbind-0.2.0-38.el7.src.rpm

**Comment by ubwa** [comment]
I am encountering the same problem on CentOS Linux release 7.3.1611 (Core) with origin 1.4.1

Has anybody got anywhere?

**Comment by harryge00** [comment]
I have deployed glusterfs as replication controllers instead of daemonset, it worked:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: gluster-1
spec:
  replicas: 1
  selector:
    app: gluster-1
  template:
    metadata:
      labels:
        app: gluster-1
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: kube-node-1
      containers:
      - image: gluster/gluster-centos
        name: gluster
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /mnt/brick1
          name: brickpath
        - name: glusterfs-heketi
          mountPath: "/var/lib/heketi"
        - name: glusterfs-run
          mountPath: "/run"
        - name: glusterfs-lvm
          mountPath: "/run/lvm"
        - name: glusterfs-etc
          mountPath: "/etc/glusterfs"
        - name: glusterfs-logs
          mountPath: "/var/log/glusterfs"
        - name: glusterfs-config
          mountPath: "/var/lib/glusterd"
        - name: glusterfs-dev
          mountPath: "/dev"
        - name: glusterfs-misc
          mountPath: "/var/lib/misc/glusterfsd"
        - name: glusterfs-cgroup
          mountPath: "/sys/fs/cgroup"
        securityContext: 
         capabilities: {}
         privileged: true
      volumes:
      - name: brickpath
        hostPath:
          path: "/mnt/brick1"
      - name: glusterfs-heketi
        hostPath:
          path: "/var/lib/heketi"
      - name: glusterfs-run
      - name: glusterfs-lvm
        hostPath:
          path: "/run/lvm"
      - name: glusterfs-etc
        hostPath:
          path: "/etc/glusterfs"
      - name: glusterfs-logs
        hostPath:
          path: "/var/log/glusterfs"
      - name: glusterfs-config
        hostPath:
          path: "/var/lib/glusterd"
      - name: glusterfs-dev
        hostPath:
          path: "/dev"
      - name: glusterfs-misc
        hostPath:
          path: "/var/lib/misc/glusterfsd"
      - name: glusterfs-cgroup
        hostPath:
          path: "/sys/fs/cgroup"
```
But you have to manually pin glusterfs to kubernetes nodes.
