### ISSUE TITLE
Lost cluster after node reboot

### ISSUE THREAD

**Issue by roffe** [heketi/heketi#821]
So all of a sudden after a node reboot the heketi service has forgotten my cluster

I followed your instructions on https://github.com/heketi/heketi/wiki/Kubernetes-Integratio
as close as possible but had to improvise some due to lacking files referenced in your documentation. (https://github.com/heketi/heketi/issues/820)

After the node reboot where the heketi servie was running i am now getting 
```
➜  heketi git:(master) ✗ heketi-cli cluster info
Error: Cluster id missing
```
How do one recover the cluster without loosing any volumes provisioned in it already?

**Comment by wernergillmer** [comment]
@roffe did you manage to fix this?

**Comment by mjudeikis** [comment]
Did you lost a cluster or Just heketi lost botlDB backend?

**Comment by wernergillmer** [comment]
I have a similar problem, when heketi get's rescheduled to another node, the boltdb is gone.

**Comment by mjudeikis** [comment]
@wernergillmer how did you deployed heleti? ansible or manual deployment? BotlDB is file-based Database, by "design" (which in my humble opinion is wrong) it "backed" into gluster itself. If you deployed manually you might miss it. 
`oc get dc heketi-storage -o yaml` should give you answer.

```
volumes:
      - glusterfs:
          endpoints: heketi-db-storage-endpoints
          path: heketidbstorage
        name: db
      - name: config
        secret:
          defaultMode: 420
          secretName: heketi-storage-config-secret
```
