### ISSUE TITLE
heketi fails on OCP Mixed deployment

### ISSUE THREAD

**Issue by mjudeikis** [heketi/heketi#848]
When deploying heketi with external gluster cluster copy job does not even start with reason:
```
   Error creating: pods "heketi-storage-copy-job-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.containers[0].securityContext.volumes[0]: Invalid value: "glusterfs": glusterfs volumes are not allowed to be used]
```

Because it requires privileged to run and Job does not have ref into which service account it should use to run:
```
spec:
  securityContext: {}
  serviceAccount: heketi-storage-service-account
  serviceAccountName: heketi-storage-service-account
```

So it "kills" all play. 

How to replicate:

1. Create external gluster cluster
2. Setup ansible to use it for storage and deploy heketi in ocp.
3. run play.
```
#gluster part 
openshift_storage_glusterfs_is_native=False
openshift_storage_glusterfs_heketi_is_native=True 
openshift_storage_glusterfs_heketi_executor=ssh 
openshift_storage_glusterfs_heketi_ssh_keyfile=/home/mjudeiki/.ssh/id_rsa
```
Version:
```
-bash-4.2# oc version
oc v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.ocpcluster.local:8443
openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
```
